import {
  Deal,
  Company,
  Contact,
  Firm,
  Sector,
  Activity,
  Indication,
  ActivityType,
} from "@/types";

// ============================================================
// SECTORS
// ============================================================

export const sectors: Sector[] = [
  { id: "s1", name: "Industrials" },
  { id: "s2", name: "Healthcare" },
  { id: "s3", name: "Technology" },
  { id: "s4", name: "Financial Services" },
  { id: "s5", name: "Consumer" },
  { id: "s6", name: "Business Services" },
  { id: "s7", name: "Energy" },
  { id: "s8", name: "Education" },
];

// ============================================================
// FIRMS
// ============================================================

export const firms: Firm[] = [
  {
    id: "f0",
    name: "Trest Capital",
    firmType: "pe_fund",
    hqCity: "New York",
    hqState: "NY",
    aumMm: 4200,
    description: "Strategic capital advisory for venture-backed leaders. Capital strategy, secondary execution, and complex capital stack solutions.",
  },
  {
    id: "f1",
    name: "Goldman Sachs",
    firmType: "investment_bank",
    hqCity: "New York",
    hqState: "NY",
    description: "Global investment bank",
  },
  {
    id: "f2",
    name: "KKR",
    firmType: "pe_fund",
    hqCity: "New York",
    hqState: "NY",
    aumMm: 528000,
  },
  {
    id: "f3",
    name: "Evercore",
    firmType: "investment_bank",
    hqCity: "New York",
    hqState: "NY",
  },
  {
    id: "f4",
    name: "Thoma Bravo",
    firmType: "pe_fund",
    hqCity: "San Francisco",
    hqState: "CA",
    aumMm: 143000,
  },
  {
    id: "f5",
    name: "Morgan Stanley",
    firmType: "investment_bank",
    hqCity: "New York",
    hqState: "NY",
  },
  {
    id: "f6",
    name: "Vista Equity Partners",
    firmType: "pe_fund",
    hqCity: "Austin",
    hqState: "TX",
    aumMm: 101000,
  },
  {
    id: "f7",
    name: "Lazard",
    firmType: "advisory",
    hqCity: "New York",
    hqState: "NY",
  },
  {
    id: "f8",
    name: "Bain Capital",
    firmType: "pe_fund",
    hqCity: "Boston",
    hqState: "MA",
    aumMm: 180000,
  },
  {
    id: "f9",
    name: "Houlihan Lokey",
    firmType: "investment_bank",
    hqCity: "Los Angeles",
    hqState: "CA",
  },
  {
    id: "f10",
    name: "Warburg Pincus",
    firmType: "pe_fund",
    hqCity: "New York",
    hqState: "NY",
    aumMm: 83000,
  },
];

// ============================================================
// CONTACTS
// ============================================================

export const contacts: Contact[] = [
  {
    id: "c1",
    firstName: "James",
    lastName: "Chen",
    email: "james.chen@gs.com",
    phone: "(212) 555-0142",
    title: "Managing Director, Industrials M&A",
    firmId: "f1",
    firm: firms[1],
    isActive: true,
    lastContactedAt: "2026-04-01T10:30:00Z",
  },
  {
    id: "c2",
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@kkr.com",
    phone: "(212) 555-0198",
    title: "Partner, Americas PE",
    firmId: "f2",
    firm: firms[2],
    isActive: true,
    lastContactedAt: "2026-03-31T16:00:00Z",
  },
  {
    id: "c3",
    firstName: "David",
    lastName: "Park",
    email: "david.park@evercore.com",
    phone: "(212) 555-0256",
    title: "Senior Managing Director, Healthcare",
    firmId: "f3",
    firm: firms[3],
    isActive: true,
    lastContactedAt: "2026-03-31T14:00:00Z",
  },
  {
    id: "c4",
    firstName: "Michael",
    lastName: "Torres",
    email: "mtorres@atlasautomation.com",
    phone: "(312) 555-0371",
    title: "CEO",
    isActive: true,
    lastContactedAt: "2026-03-28T11:00:00Z",
  },
  {
    id: "c5",
    firstName: "Rachel",
    lastName: "Kim",
    email: "rkim@beaconhealth.com",
    phone: "(415) 555-0489",
    title: "CFO",
    isActive: true,
    lastContactedAt: "2026-03-30T09:00:00Z",
  },
  {
    id: "c6",
    firstName: "Andrew",
    lastName: "Walsh",
    email: "andrew.walsh@ms.com",
    phone: "(212) 555-0523",
    title: "Managing Director, Tech M&A",
    firmId: "f5",
    firm: firms[5],
    isActive: true,
    lastContactedAt: "2026-03-29T15:30:00Z",
  },
  {
    id: "c7",
    firstName: "Lisa",
    lastName: "Patel",
    email: "lpatel@thomabravo.com",
    phone: "(415) 555-0612",
    title: "Partner",
    firmId: "f4",
    firm: firms[4],
    isActive: true,
    lastContactedAt: "2026-03-31T11:00:00Z",
  },
  {
    id: "c8",
    firstName: "Robert",
    lastName: "Chen",
    email: "robert.chen@lazard.com",
    phone: "(212) 555-0734",
    title: "Director, Financial Sponsors",
    firmId: "f7",
    firm: firms[7],
    isActive: true,
    lastContactedAt: "2026-04-01T08:45:00Z",
  },
  {
    id: "c9",
    firstName: "Emma",
    lastName: "Rodriguez",
    email: "erodriguez@vistaequity.com",
    phone: "(512) 555-0891",
    title: "Vice President",
    firmId: "f6",
    firm: firms[6],
    isActive: true,
    lastContactedAt: "2026-03-28T13:00:00Z",
  },
  {
    id: "c10",
    firstName: "Thomas",
    lastName: "Wright",
    email: "twright@meridiancp.com",
    phone: "(212) 555-0945",
    title: "Operating Partner",
    firmId: "f0",
    firm: firms[0],
    isActive: true,
    lastContactedAt: "2026-04-01T09:00:00Z",
  },
  {
    id: "c11",
    firstName: "Jennifer",
    lastName: "Liu",
    email: "jliu@baincapital.com",
    phone: "(617) 555-1023",
    title: "Principal",
    firmId: "f8",
    firm: firms[8],
    isActive: true,
    lastContactedAt: "2026-03-27T10:00:00Z",
  },
  {
    id: "c12",
    firstName: "Marcus",
    lastName: "Thompson",
    email: "mthompson@houlihanlokey.com",
    phone: "(310) 555-1156",
    title: "Managing Director, Industrials",
    firmId: "f9",
    firm: firms[9],
    isActive: true,
    lastContactedAt: "2026-03-30T16:30:00Z",
  },
];

// ============================================================
// COMPANIES
// ============================================================

export const companies: Company[] = [
  {
    id: "co1",
    name: "Atlas Automation Systems",
    codename: "Project Atlas",
    description: "Industrial automation and robotics platform serving automotive and aerospace OEMs",
    sectorId: "s1",
    sector: sectors[0],
    hqCity: "Chicago",
    hqState: "IL",
    revenueMm: 340,
    ebitdaMm: 72,
    employeeCount: 1200,
    yearFounded: 2008,
  },
  {
    id: "co2",
    name: "Beacon Health Systems",
    codename: "Project Beacon",
    description: "Cloud-based EHR and practice management SaaS for mid-size health systems",
    sectorId: "s2",
    sector: sectors[1],
    hqCity: "San Francisco",
    hqState: "CA",
    revenueMm: 185,
    ebitdaMm: 42,
    employeeCount: 620,
    yearFounded: 2014,
  },
  {
    id: "co3",
    name: "Citadel Financial Infrastructure",
    codename: "Project Citadel",
    description: "Core banking middleware and payment processing for regional banks",
    sectorId: "s4",
    sector: sectors[3],
    hqCity: "Charlotte",
    hqState: "NC",
    revenueMm: 520,
    ebitdaMm: 135,
    employeeCount: 2100,
    yearFounded: 2001,
    ownerFirmId: "f2",
    ownerFirm: firms[2],
  },
  {
    id: "co4",
    name: "Delta Specialty Chemicals",
    codename: "Project Delta",
    description: "Specialty coatings and adhesives for industrial applications",
    sectorId: "s1",
    sector: sectors[0],
    hqCity: "Houston",
    hqState: "TX",
    revenueMm: 120,
    ebitdaMm: 28,
    employeeCount: 380,
    yearFounded: 1995,
  },
  {
    id: "co5",
    name: "Eclipse Cyber",
    codename: "Project Eclipse",
    description: "Enterprise cybersecurity platform with AI-driven threat detection",
    sectorId: "s3",
    sector: sectors[2],
    hqCity: "Austin",
    hqState: "TX",
    revenueMm: 275,
    ebitdaMm: 58,
    employeeCount: 890,
    yearFounded: 2016,
  },
  {
    id: "co6",
    name: "Frontier Learning",
    codename: "Project Frontier",
    description: "K-12 EdTech marketplace connecting tutors with school districts",
    sectorId: "s8",
    sector: sectors[7],
    hqCity: "Denver",
    hqState: "CO",
    revenueMm: 65,
    ebitdaMm: 8,
    employeeCount: 180,
    yearFounded: 2019,
  },
  {
    id: "co7",
    name: "Genesis InsurTech",
    codename: "Project Genesis",
    description: "Policy administration and claims automation for P&C carriers",
    sectorId: "s4",
    sector: sectors[3],
    hqCity: "Hartford",
    hqState: "CT",
    revenueMm: 210,
    ebitdaMm: 52,
    employeeCount: 750,
    yearFounded: 2012,
  },
  {
    id: "co8",
    name: "Horizon Analytics",
    codename: "Project Horizon",
    description: "Enterprise data analytics and BI platform for Fortune 500",
    sectorId: "s3",
    sector: sectors[2],
    hqCity: "Seattle",
    hqState: "WA",
    revenueMm: 145,
    ebitdaMm: 35,
    employeeCount: 520,
    yearFounded: 2015,
  },
];

// ============================================================
// DEALS
// ============================================================

export const deals: Deal[] = [
  {
    id: "d1",
    title: "Project Atlas",
    companyId: "co1",
    company: companies[0],
    stage: "due_diligence",
    dealType: "platform",
    enterpriseValueMm: 850,
    equityCheckMm: 425,
    sourceFirmId: "f1",
    sourceFirm: firms[1],
    sourceContactId: "c1",
    sourceContact: contacts[0],
    description: "Sell-side mandate from Goldman. Industrial automation platform with strong recurring revenue from service contracts.",
    thesis: "Consolidation play in fragmented industrial automation space. 3 identified bolt-on targets. Path to $150M+ EBITDA within 3 years.",
    priority: 1,
    expectedCloseDate: "2026-07-15",
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-31T00:00:00Z",
  },
  {
    id: "d2",
    title: "Project Beacon",
    companyId: "co2",
    company: companies[1],
    stage: "management_meeting",
    dealType: "platform",
    enterpriseValueMm: 420,
    equityCheckMm: 210,
    sourceFirmId: "f3",
    sourceFirm: firms[3],
    sourceContactId: "c3",
    sourceContact: contacts[2],
    description: "Proprietary introduction via Evercore. Healthcare IT SaaS with 95% gross retention.",
    thesis: "Healthcare IT digitization tailwind. Net revenue retention 115%+. Add telehealth and patient engagement modules.",
    priority: 2,
    expectedCloseDate: "2026-09-01",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-30T00:00:00Z",
  },
  {
    id: "d3",
    title: "Project Citadel",
    companyId: "co3",
    company: companies[2],
    stage: "loi_bid",
    dealType: "co_invest",
    enterpriseValueMm: 1200,
    equityCheckMm: 200,
    sourceFirmId: "f2",
    sourceFirm: firms[2],
    sourceContactId: "c2",
    sourceContact: contacts[1],
    description: "Co-invest alongside KKR. Financial infrastructure with deep moat in regional banking.",
    thesis: "Mission-critical infrastructure with 99%+ retention. Real-time payments migration creates upsell opportunity.",
    priority: 1,
    expectedCloseDate: "2026-06-01",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "d4",
    title: "Project Delta",
    companyId: "co4",
    company: companies[3],
    stage: "initial_review",
    dealType: "bolt_on",
    enterpriseValueMm: 275,
    equityCheckMm: 140,
    sourceFirmId: "f9",
    sourceFirm: firms[9],
    sourceContactId: "c12",
    sourceContact: contacts[11],
    description: "Potential bolt-on for Atlas platform. Specialty chemicals with margin expansion opportunity.",
    thesis: "Cross-sell into Atlas customer base. Consolidate manufacturing footprint for 300bps margin uplift.",
    priority: 3,
    expectedCloseDate: "2026-10-01",
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-28T00:00:00Z",
  },
  {
    id: "d5",
    title: "Project Eclipse",
    companyId: "co5",
    company: companies[4],
    stage: "due_diligence",
    dealType: "platform",
    enterpriseValueMm: 650,
    equityCheckMm: 325,
    sourceFirmId: "f5",
    sourceFirm: firms[5],
    sourceContactId: "c6",
    sourceContact: contacts[5],
    description: "Competitive process run by Morgan Stanley. 6 sponsors in round 2.",
    thesis: "Cybersecurity spend growing 15%+ annually. AI-native platform is a differentiator. Federal contracts provide revenue floor.",
    priority: 2,
    expectedCloseDate: "2026-08-15",
    createdAt: "2026-02-20T00:00:00Z",
    updatedAt: "2026-03-31T00:00:00Z",
  },
  {
    id: "d6",
    title: "Project Frontier",
    companyId: "co6",
    company: companies[5],
    stage: "sourced",
    dealType: "growth_equity",
    enterpriseValueMm: 180,
    equityCheckMm: 75,
    description: "Inbound from founder. EdTech marketplace with strong unit economics but early stage.",
    thesis: "Category-defining marketplace. Need to validate retention post-COVID normalization.",
    priority: 4,
    createdAt: "2026-03-28T00:00:00Z",
    updatedAt: "2026-03-28T00:00:00Z",
  },
  {
    id: "d7",
    title: "Project Genesis",
    companyId: "co7",
    company: companies[6],
    stage: "exclusivity",
    dealType: "platform",
    enterpriseValueMm: 520,
    equityCheckMm: 260,
    sourceFirmId: "f7",
    sourceFirm: firms[7],
    sourceContactId: "c8",
    sourceContact: contacts[7],
    description: "Won exclusivity last week. InsurTech platform with deep carrier relationships.",
    thesis: "P&C carriers modernizing legacy systems. $50B+ TAM. Path to Rule of 40 with margin expansion.",
    priority: 1,
    expectedCloseDate: "2026-05-15",
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "d8",
    title: "Project Horizon",
    companyId: "co8",
    company: companies[7],
    stage: "initial_review",
    dealType: "platform",
    enterpriseValueMm: 340,
    equityCheckMm: 170,
    sourceFirmId: "f4",
    sourceFirm: firms[4],
    sourceContactId: "c7",
    sourceContact: contacts[6],
    description: "Thoma Bravo looking to exit. Competitive process starting Q2.",
    thesis: "Strong enterprise analytics platform. AI copilot features driving NRR expansion. Need to assess competitive positioning vs. Databricks.",
    priority: 3,
    expectedCloseDate: "2026-11-01",
    createdAt: "2026-03-25T00:00:00Z",
    updatedAt: "2026-03-31T00:00:00Z",
  },
  {
    id: "d9",
    title: "Project Keystone",
    companyId: "co5",
    company: companies[4],
    stage: "due_diligence",
    dealType: "secondary_direct",
    enterpriseValueMm: 45,
    equityCheckMm: 45,
    sourceFirmId: "f5",
    sourceFirm: firms[5],
    sourceContactId: "c6",
    sourceContact: contacts[5],
    description: "Direct secondary — early employee and Series A investor looking for liquidity. Company-approved transfer window opening May 2026.",
    thesis: "Eclipse Cyber at a 25% discount to last round. Strong growth trajectory. Company approved, clean transfer. ROFR waiver expected.",
    priority: 2,
    expectedCloseDate: "2026-06-15",
    secondaryDetails: {
      fundName: undefined,
      sellerType: "employee",
      lastRoundValuationMm: 650,
      impliedValuationMm: 490,
      discountPct: 25,
      rofr: true,
      boardApprovalRequired: true,
      shareClass: "Common (converted from options)",
    },
    createdAt: "2026-03-15T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "d10",
    title: "Project Lantern",
    stage: "loi_bid",
    dealType: "gp_led",
    enterpriseValueMm: 320,
    equityCheckMm: 80,
    sourceFirmId: "f10",
    sourceFirm: firms[10],
    description: "GP-led continuation vehicle. Warburg Pincus rolling a top-performing business services asset into a new vehicle. Seeking new LP capital.",
    thesis: "Continuation fund for high-performing asset. 2.5x MOIC to date. GP signaling strong conviction with significant re-up. Attractive entry for secondary capital.",
    priority: 1,
    expectedCloseDate: "2026-05-30",
    secondaryDetails: {
      fundName: "Warburg Pincus Fund XII",
      vintageYear: 2019,
      navMm: 320,
      discountPct: 8,
      sellerType: "gp",
      rofr: false,
      boardApprovalRequired: false,
    },
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "d11",
    title: "Project Meridian",
    stage: "sourced",
    dealType: "tender_offer",
    enterpriseValueMm: 150,
    equityCheckMm: 150,
    sourceFirmId: "f7",
    sourceFirm: firms[7],
    sourceContactId: "c8",
    sourceContact: contacts[7],
    description: "Company-run tender offer for Frontier Learning. Board-approved program to provide liquidity to early investors and employees.",
    thesis: "Structured tender at last round pricing. Clean process, company-sanctioned. Good entry point given improving unit economics post-COVID normalization.",
    priority: 3,
    expectedCloseDate: "2026-08-01",
    secondaryDetails: {
      sellerType: "founder",
      lastRoundValuationMm: 180,
      impliedValuationMm: 150,
      discountPct: 17,
      rofr: true,
      boardApprovalRequired: true,
      shareClass: "Series B Preferred",
    },
    createdAt: "2026-03-30T00:00:00Z",
    updatedAt: "2026-03-31T00:00:00Z",
  },
];

// ============================================================
// ACTIVITIES
// ============================================================

const now = new Date("2026-04-01T18:00:00Z");
function hoursAgo(h: number): string {
  return new Date(now.getTime() - h * 3600000).toISOString();
}

export const activities: Activity[] = [
  {
    id: "a1",
    activityType: "phone_call",
    title: "Call with James Chen (GS) — Project Atlas DD update",
    summary: "Goldman confirmed management presentation materials will be ready by Friday. Buyer interest remains strong with 3 sponsors still engaged. CIM addendum on backlog coming next week.",
    dealId: "d1",
    deal: deals[0],
    companyId: "co1",
    company: companies[0],
    occurredAt: hoursAgo(2),
    durationMin: 25,
    sentiment: "positive",
    participants: [contacts[0], contacts[9]],
    actionItems: [
      { text: "Review CIM addendum when received", assignee: "Thomas Wright", done: false },
      { text: "Schedule DD workstream kickoff", assignee: "Thomas Wright", dueDate: "2026-04-04", done: false },
    ],
    createdAt: hoursAgo(2),
  },
  {
    id: "a2",
    activityType: "video_meeting",
    title: "IC discussion — Project Citadel LOI terms",
    summary: "IC approved LOI at $1.2B EV (6.5x forward revenue). KKR co-invest allocation confirmed at $200M equity. Legal drafting LOI tonight. Need to submit by Thursday EOD.",
    dealId: "d3",
    deal: deals[2],
    companyId: "co3",
    company: companies[2],
    occurredAt: hoursAgo(4),
    durationMin: 45,
    sentiment: "positive",
    participants: [contacts[9], contacts[1]],
    actionItems: [
      { text: "Finalize LOI with legal", assignee: "Thomas Wright", dueDate: "2026-04-03", done: false },
      { text: "Confirm KKR co-invest terms", assignee: "Sarah Mitchell", dueDate: "2026-04-02", done: false },
    ],
    createdAt: hoursAgo(4),
  },
  {
    id: "a3",
    activityType: "email",
    title: "Inbound from Robert Chen (Lazard) — new healthcare mandate",
    summary: "Lazard engaged on sell-side for a $300-400M revenue healthcare staffing platform. Preliminary materials attached. Process kicking off in 2 weeks.",
    companyId: undefined,
    occurredAt: hoursAgo(5),
    sentiment: "neutral",
    participants: [contacts[7]],
    actionItems: [
      { text: "Review teaser and discuss at Monday pipeline meeting", assignee: "Thomas Wright", dueDate: "2026-04-07", done: false },
    ],
    createdAt: hoursAgo(5),
  },
  {
    id: "a4",
    activityType: "in_person_meeting",
    title: "Management meeting — Project Beacon (Beacon Health)",
    summary: "Met with Rachel Kim (CFO) and CEO. Strong team. Revenue growth 35% YoY with improving unit economics. Key risk: customer concentration — top 5 clients are 40% of revenue. Need to dig into churn data.",
    dealId: "d2",
    deal: deals[1],
    companyId: "co2",
    company: companies[1],
    occurredAt: hoursAgo(8),
    durationMin: 90,
    sentiment: "positive",
    participants: [contacts[4], contacts[9]],
    actionItems: [
      { text: "Request detailed cohort retention data", assignee: "Thomas Wright", dueDate: "2026-04-03", done: false },
      { text: "Schedule follow-up call with CTO on product roadmap", done: false },
    ],
    createdAt: hoursAgo(8),
  },
  {
    id: "a5",
    activityType: "slack_message",
    title: "Internal — Eclipse Cyber competitive dynamics",
    summary: "Team flagged that Bain Capital dropped out of Project Eclipse process. Down to 5 sponsors. Our bid positioning looks stronger. Andrew Walsh at MS confirmed we're in top 3.",
    dealId: "d5",
    deal: deals[4],
    companyId: "co5",
    company: companies[4],
    occurredAt: hoursAgo(6),
    sentiment: "positive",
    participants: [contacts[5]],
    createdAt: hoursAgo(6),
  },
  {
    id: "a6",
    activityType: "phone_call",
    title: "Call with Lisa Patel (Thoma Bravo) — Project Horizon process",
    summary: "TB planning to launch formal process in May. Exploring dual-track IPO/sale. Expects 8-10x revenue multiple. Asked if we'd be interested in a pre-emptive bid — declined to discuss pre-process.",
    dealId: "d8",
    deal: deals[7],
    companyId: "co8",
    company: companies[7],
    occurredAt: hoursAgo(26),
    durationMin: 20,
    sentiment: "neutral",
    participants: [contacts[6]],
    actionItems: [
      { text: "Build preliminary model on Horizon", assignee: "Thomas Wright", dueDate: "2026-04-07", done: false },
    ],
    createdAt: hoursAgo(26),
  },
  {
    id: "a7",
    activityType: "internal_note",
    title: "Project Genesis — exclusivity update",
    summary: "Signed exclusivity agreement yesterday. 45-day exclusivity window. Confirmatory DD workstreams kicking off: financial, legal, commercial, IT. Targeting May 15 close.",
    dealId: "d7",
    deal: deals[6],
    companyId: "co7",
    company: companies[6],
    occurredAt: hoursAgo(10),
    sentiment: "positive",
    participants: [contacts[7], contacts[9]],
    createdAt: hoursAgo(10),
  },
  {
    id: "a8",
    activityType: "video_meeting",
    title: "Weekly pipeline review — all active deals",
    summary: "Reviewed all 8 active deals. Priority actions: (1) Submit Citadel LOI by Thursday, (2) Advance Atlas DD workstreams, (3) Make go/no-go on Frontier by next Monday. Passed on 2 inbound teasers (consumer retail, not our space).",
    occurredAt: hoursAgo(30),
    durationMin: 60,
    sentiment: "neutral",
    participants: [contacts[9]],
    createdAt: hoursAgo(30),
  },
  {
    id: "a9",
    activityType: "phone_call",
    title: "Call with Marcus Thompson (HL) — Project Delta teaser",
    summary: "Houlihan running a targeted process for Delta Specialty Chemicals. Perfect bolt-on for Atlas. $275M EV, ~$28M EBITDA. Meeting management team next week.",
    dealId: "d4",
    deal: deals[3],
    companyId: "co4",
    company: companies[3],
    occurredAt: hoursAgo(50),
    durationMin: 15,
    sentiment: "positive",
    participants: [contacts[11]],
    createdAt: hoursAgo(50),
  },
  {
    id: "a10",
    activityType: "email",
    title: "Emma Rodriguez (Vista) — potential co-invest in enterprise software",
    summary: "Vista exploring co-invest partners for a $500M+ enterprise software deal. Details under NDA. Scheduled call for next week to discuss.",
    occurredAt: hoursAgo(72),
    sentiment: "neutral",
    participants: [contacts[8]],
    actionItems: [
      { text: "Sign NDA and schedule call with Vista team", dueDate: "2026-04-04", done: false },
    ],
    createdAt: hoursAgo(72),
  },
];

// ============================================================
// INDICATIONS
// ============================================================

export const indications: Indication[] = [
  // ---- RELATIONSHIP-SOURCED (from calls/meetings) ----
  {
    id: "i1",
    side: "sell",
    firmId: "f4",
    firm: firms[4],
    contactId: "c7",
    contact: contacts[6],
    companyId: "co8",
    company: companies[7],
    sizeMinMm: 300,
    sizeMaxMm: 400,
    notes: "Thoma Bravo exploring exit of Horizon Analytics. Dual-track IPO/sale process expected May 2026.",
    isActive: true,
    createdAt: "2026-03-25T00:00:00Z",
    source: "relationship",
    sourceActivityId: "a6",
    confidence: 0.95,
    reviewed: true,
  },
  {
    id: "i2",
    side: "buy",
    firmId: "f2",
    firm: firms[2],
    contactId: "c2",
    contact: contacts[1],
    sectorId: "s4",
    sector: sectors[3],
    sizeMinMm: 500,
    sizeMaxMm: 2000,
    notes: "KKR actively seeking financial infrastructure platforms. Looking for co-invest partners on larger deals.",
    isActive: true,
    createdAt: "2026-03-15T00:00:00Z",
    source: "relationship",
    sourceActivityId: "a2",
    confidence: 0.9,
    reviewed: true,
  },
  {
    id: "i3",
    side: "buy",
    firmId: "f6",
    firm: firms[6],
    contactId: "c9",
    contact: contacts[8],
    sectorId: "s3",
    sector: sectors[2],
    sizeMinMm: 300,
    sizeMaxMm: 800,
    notes: "Vista looking for enterprise software add-ons. Focus on vertical SaaS with $20M+ ARR.",
    isActive: true,
    createdAt: "2026-03-18T00:00:00Z",
    source: "relationship",
    sourceActivityId: "a10",
    confidence: 0.85,
    reviewed: true,
  },
  {
    id: "i4",
    side: "sell",
    firmId: "f1",
    firm: firms[1],
    contactId: "c1",
    contact: contacts[0],
    companyId: "co1",
    company: companies[0],
    sizeMinMm: 700,
    sizeMaxMm: 1000,
    notes: "Goldman running sell-side for Atlas Automation. Management presentations ongoing. Bids due April 30.",
    isActive: true,
    createdAt: "2026-02-10T00:00:00Z",
    source: "relationship",
    sourceActivityId: "a1",
    confidence: 1.0,
    reviewed: true,
  },
  // ---- MANUAL ENTRY ----
  {
    id: "i5",
    side: "buy",
    firmId: "f8",
    firm: firms[8],
    contactId: "c11",
    contact: contacts[10],
    sectorId: "s2",
    sector: sectors[1],
    sizeMinMm: 200,
    sizeMaxMm: 600,
    notes: "Bain Capital healthcare team looking for health IT platforms. Prefer SaaS models with 90%+ gross retention.",
    isActive: true,
    createdAt: "2026-03-10T00:00:00Z",
    source: "manual",
    confidence: 1.0,
    reviewed: true,
  },
  {
    id: "i6",
    side: "sell",
    firmId: "f7",
    firm: firms[7],
    contactId: "c8",
    contact: contacts[7],
    sectorId: "s2",
    sector: sectors[1],
    sizeMinMm: 300,
    sizeMaxMm: 500,
    notes: "New Lazard healthcare staffing mandate. Process kicking off mid-April.",
    isActive: true,
    createdAt: "2026-04-01T00:00:00Z",
    source: "relationship",
    sourceActivityId: "a3",
    confidence: 0.92,
    reviewed: true,
  },
  {
    id: "i7",
    side: "both",
    firmId: "f10",
    firm: firms[10],
    contactId: undefined,
    sectorId: "s6",
    sector: sectors[5],
    sizeMinMm: 200,
    sizeMaxMm: 500,
    notes: "Warburg Pincus business services team active. Looking to deploy from Fund XIV. Also exploring exits from older vintage portfolio.",
    isActive: true,
    createdAt: "2026-03-20T00:00:00Z",
    source: "manual",
    confidence: 1.0,
    reviewed: true,
  },
  // ---- WEB INTELLIGENCE (auto-scraped) ----
  {
    id: "i8",
    side: "sell",
    sectorId: "s3",
    sector: sectors[2],
    notes: "SEC Form D filing: Cybersecurity firm Eclipse Cyber filed a new Form D for a $75M secondary offering. Transfer agent: Carta. Filing date March 28, 2026.",
    isActive: true,
    createdAt: "2026-03-29T00:00:00Z",
    source: "web_intel",
    webIntelType: "sec_filing",
    webIntelUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany",
    confidence: 0.88,
    reviewed: false,
  },
  {
    id: "i9",
    side: "sell",
    sectorId: "s4",
    sector: sectors[3],
    notes: "Press release: CalPERS announced $3B portfolio rebalancing program, divesting select PE fund stakes. Focus on reducing exposure to 2017–2019 vintage buyout funds.",
    isActive: true,
    createdAt: "2026-03-31T00:00:00Z",
    source: "web_intel",
    webIntelType: "press_release",
    webIntelUrl: "https://www.calpers.ca.gov/page/newsroom",
    confidence: 0.82,
    reviewed: false,
  },
  {
    id: "i10",
    side: "buy",
    sectorId: "s2",
    sector: sectors[1],
    notes: "PitchBook data: Bain Capital raised $4.6B for Fund XIV dedicated to healthcare services. Fund close announced March 2026. Active deployment expected Q2–Q3.",
    isActive: true,
    createdAt: "2026-03-28T00:00:00Z",
    source: "web_intel",
    webIntelType: "fund_data",
    webIntelUrl: "https://pitchbook.com/profiles/bain-capital",
    confidence: 0.91,
    reviewed: false,
  },
  {
    id: "i11",
    side: "sell",
    firmId: "f6",
    firm: firms[6],
    sectorId: "s3",
    sector: sectors[2],
    notes: "LinkedIn: Vista Equity Partners' Head of Portfolio Operations joined Thoma Bravo as COO. Key departure may signal changes in Vista's portfolio management approach and potential exits.",
    isActive: true,
    createdAt: "2026-04-01T00:00:00Z",
    source: "web_intel",
    webIntelType: "personnel_move",
    webIntelUrl: "https://www.linkedin.com",
    confidence: 0.65,
    reviewed: false,
  },
  {
    id: "i12",
    side: "both",
    sectorId: "s1",
    sector: sectors[0],
    notes: "Jefferies market report: Industrial automation M&A activity up 40% YoY in Q1 2026. Average EV/EBITDA multiples expanded to 14.2x from 12.8x. Strong sponsor demand with limited quality supply.",
    isActive: true,
    createdAt: "2026-03-30T00:00:00Z",
    source: "web_intel",
    webIntelType: "market_report",
    webIntelUrl: "https://www.jefferies.com/insights",
    confidence: 0.78,
    reviewed: false,
  },
  {
    id: "i13",
    side: "sell",
    sectorId: "s6",
    sector: sectors[5],
    notes: "Bloomberg: Warburg Pincus exploring continuation vehicle for top-performing business services portfolio company. Lazard and Evercore advising. Expected close Q2 2026.",
    isActive: true,
    createdAt: "2026-03-27T00:00:00Z",
    source: "web_intel",
    webIntelType: "news_article",
    webIntelUrl: "https://www.bloomberg.com/news",
    confidence: 0.87,
    reviewed: true,
  },
  // ---- RELATIONSHIP-EXTRACTED (AI parsed from activity notes) ----
  {
    id: "i14",
    side: "buy",
    firmId: "f6",
    firm: firms[6],
    contactId: "c9",
    contact: contacts[8],
    sectorId: "s3",
    sector: sectors[2],
    sizeMinMm: 400,
    sizeMaxMm: 600,
    notes: "[Auto-extracted from email with Emma Rodriguez] Vista exploring co-invest partners for a $500M+ enterprise software deal. Details under NDA.",
    isActive: true,
    createdAt: hoursAgo(72),
    source: "relationship",
    sourceActivityId: "a10",
    confidence: 0.78,
    reviewed: false,
  },
  {
    id: "i15",
    side: "sell",
    sectorId: "s3",
    sector: sectors[2],
    notes: "[Auto-extracted from Slack] Bain Capital dropped out of Project Eclipse process. Reduces competition — down to 5 sponsors. Our bid positioning stronger.",
    isActive: true,
    createdAt: hoursAgo(6),
    source: "relationship",
    sourceActivityId: "a5",
    confidence: 0.72,
    reviewed: false,
  },
];

// ============================================================
// SUMMARY STATS
// ============================================================

export const dashboardStats = {
  activeDeals: deals.filter(
    (d) => !["closed_won", "passed", "dead"].includes(d.stage)
  ).length,
  totalPipelineValue: deals
    .filter((d) => !["closed_won", "passed", "dead"].includes(d.stage))
    .reduce((sum, d) => sum + (d.enterpriseValueMm || 0), 0),
  activitiesThisWeek: activities.filter(
    (a) => new Date(a.occurredAt) > new Date(now.getTime() - 7 * 86400000)
  ).length,
  activeIndications: indications.filter((i) => i.isActive).length,
  dealsInDD: deals.filter((d) => d.stage === "due_diligence").length,
  dealsInLOI: deals.filter(
    (d) => d.stage === "loi_bid" || d.stage === "exclusivity"
  ).length,
};

// today's agenda items
export const todaysAgenda: Array<{
  time: string;
  title: string;
  type: ActivityType;
  deal?: string;
  participants: string[];
}> = [
  {
    time: "9:00 AM",
    title: "Morning Pipeline Standup",
    type: "video_meeting" as ActivityType,
    participants: ["Thomas Wright"],
  },
  {
    time: "10:30 AM",
    title: "Call with James Chen (GS) — Atlas DD",
    type: "phone_call" as ActivityType,
    deal: "Project Atlas",
    participants: ["James Chen", "Thomas Wright"],
  },
  {
    time: "12:00 PM",
    title: "Lunch with Sarah Mitchell (KKR)",
    type: "in_person_meeting" as ActivityType,
    deal: "Project Citadel",
    participants: ["Sarah Mitchell"],
  },
  {
    time: "2:00 PM",
    title: "IC Meeting — Citadel LOI Review",
    type: "video_meeting" as ActivityType,
    deal: "Project Citadel",
    participants: ["Thomas Wright", "Sarah Mitchell"],
  },
  {
    time: "3:30 PM",
    title: "Call with David Park (Evercore) — Beacon update",
    type: "phone_call" as ActivityType,
    deal: "Project Beacon",
    participants: ["David Park"],
  },
  {
    time: "4:30 PM",
    title: "Internal: Eclipse Cyber bid strategy",
    type: "video_meeting" as ActivityType,
    deal: "Project Eclipse",
    participants: ["Thomas Wright"],
  },
];
